// Code generated by "stringer -type Code"; DO NOT EDIT.

package er

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UncaughtException-0]
	_ = x[InvalidAppToken-1]
	_ = x[CSVFileDataFormatNotProper-2]
	_ = x[UserNotPresent-3]
	_ = x[ErrorInsertingToDatabase-4]
}

const _Code_name = "UncaughtExceptionInvalidAppTokenCSVFileDataFormatNotProperUserNotPresentErrorInsertingToDatabase"

var _Code_index = [...]uint8{0, 17, 32, 58, 72, 96}

func (i Code) String() string {
	if i < 0 || i >= Code(len(_Code_index)-1) {
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Code_name[_Code_index[i]:_Code_index[i+1]]
}
